### ISSUE TITLE
[Bug]: Server crashes while starting.

### ISSUE THREAD

**Issue by TheButterbrotMan** [Toadstool-Studios/Playdate#1]
### Bug Description

Server crashes while starting.

### Version

2.2.0

### Mod Loader Version

1.18.2 - 0.13.13

### Mod Loader

Fabric

### Logs or additional context

https://bytebin.lucko.me/zuDezpGB8W

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Fixed just pushed an update, update 2.2.1 should fix this so when it gets approved by curse you can download it.
