### ISSUE TITLE
[Bug]: Server crashed while starting server

### ISSUE THREAD

**Issue by pewblaze** [Toadstool-Studios/Playdate#2]
### Bug Description

Server crashed while starting server. Without the mod it worked fine. Not sure what happened ^^"

### Version

2.2.0

### Mod Loader Version

0.13.3

### Mod Loader

Fabric

### Logs or additional context

Log: https://pastebin.com/7UFqTQta

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Fixed just pushed an update, update 2.2.1 should fix this so when it gets approved by curse you can download it.
