### ISSUE TITLE
[Bug]: Server crashed after playing the music doll

### ISSUE THREAD

**Issue by pewblaze** [Toadstool-Studios/Playdate#3]
### Bug Description

Server crashed after playing the music doll. (right click it)

### Version

2.2.1

### Mod Loader Version

0.13.3

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/xw2SPMNm

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Fixed in latest version
