### ISSUE TITLE
[Bug]: Server crash upon drinking any vanilla potion

### ISSUE THREAD

**Issue by TNSGJones** [Toadstool-Studios/Playdate#4]
### Bug Description

The server crashes whenever a potion is used by any player. I'm not entirely sure what causes it, however, crashlogs always state "Illegal classload request for tech.thatgravyboat.playdate.mixin.ItemAccessor".

The bug is not reproducable in singleplayer
[crash-2022-04-15_11.47.46-server.txt](https://github.com/Toadstool-Studios/Playdate/files/8495799/crash-2022-04-15_11.47.46-server.txt)
.

### How to Reproduce?

1. Join server
2. consume a potion of any kind
3. server crashes

### Expected Behavior

No crashes

### Version

2.2.2

### Mod Loader Version

40.0.40

### Mod Loader

Forge

### Logs or additional context

Crashlog

[crash-2022-04-15_11.47.46-server.txt](https://github.com/Toadstool-Studios/Playdate/files/8495806/crash-2022-04-15_11.47.46-server.txt)

Log ( startup ends at [15Apr2022 11:46:52.673] )
Log is basicly server startup, setting my own gamemode to creative, grabbing a potion and drinking it in survival.

After consuming the potion, the following error appears in logs
10: ASM: class net.mehvahdjukaar.supplementaries.common.events.ServerEvents onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for tech.thatgravyboat.playdate.mixin.ItemAccessor. Mixin is defined in playdate-common.mixins.json and cannot be referenced directly
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334)
 
[2022-04-15-3.log](https://github.com/Toadstool-Studios/Playdate/files/8495813/2022-04-15-3.log)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Fixed in latest version
